### ISSUE TITLE
File "plugin.py", line 534, in webhook_proxy type: 'dict' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by Zendog** [FlyingDiver/Indigo-HTTPd-2#10]
FYI ... I got this error (below) during execution after updating to the latest version with Python 3.

I changed line 534 to use dict.items() instead of dict.iteritems() as iteritems() was removed in python3, so you can't use this method anymore. All seem to work fine after this change.

**** Error in indigo log ***

  HTTPd 2 Error                   Error in plugin execution ReceivedBroadcast:

  File "plugin.py", line 534, in webhook_proxy
type: 'dict' object has no attribute 'iteritems'

   HTTPd 2 Error                   Error in plugin execution ReceivedBroadcast:

  File "plugin.py", line 534, in webhook_proxy
type: 'dict' object has no attribute 'iteritems'

**Comment by FlyingDiver** [comment]
Try https://github.com/FlyingDiver/Indigo-HTTPd-2/releases/tag/2022.0.1

**Comment by Zendog** [comment]
Thx ...
