### ISSUE TITLE
add LastUpdate

### ISSUE THREAD

**Issue by betsim** [FlyingDiver/Indigo-HTTPd-2#5]
If I want to trigger a button click HTTPd2 works just the first time because the second time there is no change of action/index/mac. Using HTTPd(1) I used to clear the variable who triggered an action, so the second click is also a change. This workaround does not work in HTTPd2, so there could be a solution to provide the time (or a random number) every time something changed on the device.

**Comment by FlyingDiver** [comment]
Moved issue to correct Git repository.

**Comment by FlyingDiver** [comment]
https://github.com/FlyingDiver/Indigo-HTTPd-2/releases/tag/2.1.0

**Comment by betsim** [comment]
Works perfect. Thank you!!! 🎉
